### PR TITLE
Cross platform update

### PR DESCRIPTION
**Pull request by yoanhg421**
Script can be use cross platform and target Windows Mac and Linux by using net7 and building for the desired platform.
` dotnet publish -r win-x64 --sc true -f net7.0 -c release` 
`dotnet publish -r linux-x64 --sc true -f net7.0 -c release`
`dotnet publish -r osx-x64 --sc true -f net7.0 -c release `

These commands build a self contained executable file so the end user doesn't need to install the dotnet7 sdk. 
tested on Mac and arch linux on the  SteamDeck. Working as intended after the TSL1.2 was enabled on the CDN website.

### CODE REVIEW

**Comment by GG-Downloader-Win** [comment]
By removing the .NET Framework 4.8 TFM, this would break the [assumed] backwards compatibility with Windows 7 (as no version of .net [non-framework] above, I believe, 3.1 supports Windows 7) which was a target all along. I'll need to double-check that Win 7 is supported on the 4.8 build (at least, once Win 7 has TLS 1.2 enabled) and if so we'll need to keep the `.net48`  TFM in keep that backwards compatibility. Agreed if it doesn't work back to 7, it's a moot point.  Will run some testing this evening. _Or_ we'll need to see what would be involved in backporting the rest of the app back to .net core 3.1 to make Windows 7 a viable target. Give me a day or two.

**Comment by yoanhg421** [comment]
Take your time.  I thought windows 7 was out of support already by Microsoft so I didn’t  think that was a concern. We can add back the net4.8 if you need to target windows 7 specifically. It doesn’t really affect the script in any way since the build commands I sent specifically target dotnet 7. I figured anyone technically inclined enough to be using this tool wouldn’t be on windows 7 anyways but I could be wrong.

**Comment by GG-Downloader-Win** [comment]
Okay, after testing on Windows 7, I can confirm that a) it does work, but b) an additional line of code is needed, so I'll go ahead and merge this in and then submit an update with some more win 7 specifc stuff (and restore .net 4.8 at that point).

Thank you!

**Comment by quicknote4444** [comment]
@yoanhg421, a quick but important note here: Windows 7 is not out of support, Microsoft does make Windows 7 secure in 2022, does [publish](https://www.catalog.update.microsoft.com/ScopedViewInline.aspx?updateid=be14a194-01ff-4ffe-8a4a-b5d0deaa4080) updates all this time (see: [Extended Security Updates](https://learn.microsoft.com/en-us/troubleshoot/windows-client/windows-7-eos-faq/windows-7-extended-security-updates-faq)); "Technically inclined" know of Github Open Source projects making a non-enterprise Windows 7 receive it freely.

**Comment by GG-Downloader-Win** [comment]
Windows 7 was just a target goal that we picked for this project; as there's a lot of GOG games that run on Windows 7 just fine, it seemed a reasonable minimum target platform.  

With the desire for a GUI version of this [in the near future], it also becomes necessary to take into account which .NET implementation we want to rely on. .NET Framework supports Windows Desktop, obviously, as does .NET [I think] 5, [maybe it's 6]. Either way, the latest (non-Framework) .NET version that supports Windows 7 is .NET Core 3.1, which _doesn't_ support desktop apps. 

So we're stuck with effectively having to target .NET Framework 4.8 for Windows 7 GUI stuff, and .NET 6/7/etc for more modern versions of Windows' GUI stuff.  Thankfully the SDK is pretty flexible with this sort of multitargeting. Although the .NET 4.8 Framework GUI stuff works perfectly for the more modern Windows versions, I'm reticent about doing new dev work entirely in Framework 4.8 at this point; would much rather target both.

**Comment by yoanhg421** [comment]
Yes of course I agree that support should be extended as back as possible. I love windows 7 and was reluctant for a while to upgrade so it seems reasonable to keep it as a target platform. I know dotnet is cross platform as long as the application stays in a script form.  I, for example, use my Mac to download games and then transfer them to my Linux and windows machine, or sometimes I download the games straight into Linux or windows so having that option is very important to me.   If having a GUI is a big goal then it gets a little more complex.  Are you going to use Winform, WPF, UWP, Maui to build the GUI?  Only Maui is compatible with Windows 10+ and Mac, but that leaves Linux out of the picture.  Everything else only supports windows and only WinForms and WPF support windows 7 for the UI. On the other hand Flutter can target windows 7 and above, MacOS and Linux on a single codebase. 

I love this project and would love help as much as I can, regardless of the path it takes.  In the end the ultimate decision belongs to the project owner and/or the main developer.

**Comment by yoanhg421** [comment]
@quicknote4444 I mostly do Enterprise work and we phased out windows 7 years ago that is why I wasn’t sure if there is a huge need for windows 7 support as I mostly use windows 10, Mac and Linux for work.  Since there is, I would gladly help support it. However this increases complexity on the project, specially once the UI gets implemented and targeting multiple platforms is also in the road ahead. Handling multiple codebases for the same project is not an ideal scenario that is not up to me to decide. I’m just here to help in whatever I can.

**Comment by GG-Downloader-Win** [comment]
Windows 7 is fine; with it supporting .NET 4.8, and the whole .NET SDK being able to target multiple versions of the SDK together, it's no harder to keep supporting Windows 7 than just removing it. It's literally just one extra line of code. 

As far as GUIs go _unless there was a desire for a GUI for Linux and macOS_, then it's no harder to support Windows 7 than it is to remove it. Going cross-platform on a GUI may-or-may not be problematic with Windows 7, I'd have to look into the various cross-platform UI options (avalonia, wpf, etc) and see what they support.

My gut is I'd like to keep Win 7 support going as long as I can, and if there's a practical way to add Linux and macOS support for the GUI, I'd be all for that.

**Comment by yoanhg421** [comment]
I can highly recommend Flutter for cross platform UI framework.  I you go with WPF we can refactor the common code into a shared project and target the  dotnet7 console app and  WPF in a single solution.

**Comment by GG-Downloader-Win** [comment]
I'll look into it; thanks!

**Comment by quicknote4444** [comment]
@GG-Downloader-Win, GOG Store might not mention Windows 7 while in a game does work OK. Would a compatibility sheet useful for the project or should it be kept away? Likely format: Product ID, Slug, Version, Build, Installer File, Status, Comment. All the games are to be included, no exception.

**Comment by quicknote4444** [comment]
Okay nevermind silly me in the edited above message. I'll test what "GOG did not" internally, no publication for a launcher: 73 games for Windows 10, crazy 270 (!) for "not dead" (dead actually, very-very dead, prematurely) Windows 8.1, and  smaller 247 for 7 (most DirectX 11 work, the real number is highly likely far lower than what 10 actually cannot run because Microsoft screwed up compatibility), maybe will buy a time machine and test all the games for WINE compatibility. It does not mean, however, that I agree with covering up "I want to help" in "I want 'to help' to help less people run the downloader/launcher, less people have fun." I think the real help is to retain the widest compatibility possible.

Well, anyway, Good Luck You All & Bye!

**Comment by statsfantasm** [comment]
The truthful objective statistics is absolutely 100% fully on Ghost's side, folks:
- Work OK on Windows 7 in practice: 4,154 (99.44%) GOG games;
- Really* require Windows 10 to play: ~23 (0.55%) games;
\* *As in "nobody can run that on Windows 7 by default" (even me): Windows 10 is required to run, Windows 7 throws errors*
- Are made & released in 2020 plus: ~977 (23.38%) games;
- In 2022 plus, formally do support Windows 7: ~737 (75.43% of 977) Games;
- In 2022 plus, formally no Windows 7 support: ~240 (24.56% of 977) Games;
- In 2022 plus, state fake system requirements: ~217 (90.41% of 240, 22.21% of 977) Games.

Some persons may desire to make-belief the false deceptive perception as if Windows 10 is "required" to run most modern games, to excuse the blatant ignorance or negligence on own GOG collections. Does it stand a test in practice? It does not. The truth is plain and simple: The vast majority of games do support Windows 7 formally, many new do support Windows 7 in reality. This is exactly what smart Ghost felt and saw correctly.

**Comment by yoanhg421** [comment]
Yes. I’ll be happy to help

**Comment by mx-ghost** [comment]
Ain't a Mr. though. Please let's be objective and not impose yours on others.

On the project, if you'll do a translation, I could help on adding 1 new language, sharing info on testing game compatibility like the above can be done too, maybe some other feedback. If you are available on [Matrix](https://app.element.io/) (Chat, no phone number req) and want to talk about GG, the new GG site API (the downloader should take into account or may break), on messy GOG itself and to know what's actually missing on GG (new games, DLCs & updates are tracked by a special 3rd party site), including some other specific GOG things, then may write to statsfantasm@proton.me for further details (the address will be not in use after a few days or a week). If not, alright, to each their own.

**Pull request merged**
